/* Write SQL queries to perform the following tasks using the Sakila database:

List the number of films per category. */

SELECT category_id, COUNT(title)
FROM sakila.film_category
INNER JOIN sakila.film
ON sakila.film_category.film_id = sakila.film.film_id
GROUP BY category_id;

/*Retrieve the store ID, city, and country for each store.*/

SELECT *
FROM sakila.city;

SELECT *
FROM sakila.country;

SELECT *
FROM sakila.store;

/*I coundn't do it.*/

/*Calculate the total revenue generated by each store in dollars.*/

SELECT store, total_sales
FROM sakila.sales_by_store;

/*Determine the average running time of films for each category. */

SELECT category_id, AVG(length)
FROM sakila.film_category
INNER JOIN sakila.film
ON sakila.film_category.film_id = sakila.film.film_id
GROUP BY category_id
